package app.controller;

import java.util.Hashtable;

import javafx.scene.Parent;

public class Cards {
	Hashtable<Integer, String> CardsName = new Hashtable<>();
	Hashtable<Integer, Integer> CardsValue = new Hashtable<>();
	
	public Cards() {
	  
			CardsValue.put(1, 2);
			CardsValue.put(2, 3);
			CardsValue.put(3, 4);
			CardsValue.put(4, 5);
			CardsValue.put(5, 6);
			CardsValue.put(6, 7);
			CardsValue.put(7, 8);
			CardsValue.put(8, 9);
			CardsValue.put(9, 10);
			CardsValue.put(10, 10);
			CardsValue.put(11, 10);
			CardsValue.put(12, 10);
			CardsValue.put(13, 11);
			CardsValue.put(14, 2);
			CardsValue.put(15, 3);
			CardsValue.put(16, 4);
			CardsValue.put(17, 5);
			CardsValue.put(18, 6);
			CardsValue.put(19, 7);
			CardsValue.put(20, 8);
			CardsValue.put(21, 9);
			CardsValue.put(22, 10);
			CardsValue.put(23, 10);
			CardsValue.put(24, 10);
			CardsValue.put(25, 10);
			CardsValue.put(26, 11);
			CardsValue.put(27, 2);
			CardsValue.put(28, 3);
			CardsValue.put(29, 4);
			CardsValue.put(30, 5);
			CardsValue.put(31, 6);
			CardsValue.put(32, 7);
			CardsValue.put(33, 8);
			CardsValue.put(34, 9);
			CardsValue.put(35, 10);
			CardsValue.put(36, 10);
			CardsValue.put(37, 10);
			CardsValue.put(38, 10);
			CardsValue.put(39, 11);
			CardsValue.put(40, 2);
			CardsValue.put(41, 3);
			CardsValue.put(42, 4);
			CardsValue.put(43, 5);
			CardsValue.put(44, 6);
			CardsValue.put(45, 7);
			CardsValue.put(46, 8);
			CardsValue.put(47, 9);
			CardsValue.put(48, 10);
			CardsValue.put(49, 10);
			CardsValue.put(50, 10);
			CardsValue.put(51, 10);
			CardsValue.put(52, 11);
			/*CardsValue.put(53, 2);
			CardsValue.put(54, 3);
			CardsValue.put(55, 4);
			CardsValue.put(56, 5);
			CardsValue.put(57, 6);
			CardsValue.put(58, 7);
			CardsValue.put(59, 8);
			CardsValue.put(60, 9);
			CardsValue.put(61, 10);
			CardsValue.put(62, 10);
			CardsValue.put(63, 10);
			CardsValue.put(64, 10);
			CardsValue.put(65, 11);
			CardsValue.put(66, 2);
			CardsValue.put(67, 3);
			CardsValue.put(68, 4);
			CardsValue.put(69, 5);
			CardsValue.put(70, 6);
			CardsValue.put(71, 7);
			CardsValue.put(72, 8);
			CardsValue.put(73, 9);
			CardsValue.put(74, 10);
			CardsValue.put(75, 10);
			CardsValue.put(76, 10);
			CardsValue.put(77, 10);
			CardsValue.put(78, 11);
			CardsValue.put(79, 2);
			CardsValue.put(80, 3);
			CardsValue.put(81, 4);
			CardsValue.put(82, 5);
			CardsValue.put(83, 6);
			CardsValue.put(84, 7);
			CardsValue.put(85, 8);
			CardsValue.put(86, 9);
			CardsValue.put(87, 10);
			CardsValue.put(88, 10);
			CardsValue.put(89, 10);
			CardsValue.put(90, 10);
			CardsValue.put(91, 11);
			CardsValue.put(92, 2);
			CardsValue.put(93, 3);
			CardsValue.put(94, 4);
			CardsValue.put(95, 5);
			CardsValue.put(96, 6);
			CardsValue.put(97, 7);
			CardsValue.put(98, 8);
			CardsValue.put(99, 9);
			CardsValue.put(100, 10);
			CardsValue.put(101, 10);
			CardsValue.put(102, 10);
			CardsValue.put(103, 10);
			CardsValue.put(104, 11);*/
			
			CardsName.put(1, "2 clubs");
			CardsName.put(2, "3 clubs");
			CardsName.put(3, "4 clubs");
			CardsName.put(4, "5 clubs");
			CardsName.put(5, "6 clubs");
			CardsName.put(6, "7 clubs");
			CardsName.put(7, "8 clubs");
			CardsName.put(8, "9 clubs");
			CardsName.put(9, "10 clubs");
			CardsName.put(10, "Jack clubs");
			CardsName.put(11, "Queen clubs");
			CardsName.put(12, "King clubs");
			CardsName.put(13, "Ace clubs");
			CardsName.put(14, "2 diamonds");
			CardsName.put(15, "3 diamonds");
			CardsName.put(16, "4 diamonds");
			CardsName.put(17, "5 diamonds");
			CardsName.put(18, "6 diamonds");
			CardsName.put(19, "7 diamonds");
			CardsName.put(20, "8 diamonds");
			CardsName.put(21, "9 diamonds");
			CardsName.put(22, "10 diamonds");
			CardsName.put(23, "Jack diamonds");
			CardsName.put(24, "Queen diamonds");
			CardsName.put(25, "King diamonds");
			CardsName.put(26, "Ace diamonds");
			CardsName.put(27, "2 hearts");
			CardsName.put(28, "3 hearts");
			CardsName.put(29, "4 hearts");
			CardsName.put(30, "5 hearts");
			CardsName.put(31, "6 hearts");
			CardsName.put(32, "7 hearts");
			CardsName.put(33, "8 hearts");
			CardsName.put(34, "9 hearts");
			CardsName.put(35, "10 hearts");
			CardsName.put(36, "Jack hearts");
			CardsName.put(37, "Queen hearts");
			CardsName.put(38, "King hearts");
			CardsName.put(39, "Ace hearts");
			CardsName.put(40, "2 spades");
			CardsName.put(41, "3 spades");
			CardsName.put(42, "4 spades");
			CardsName.put(43, "5 spades");
			CardsName.put(44, "6 spades");
			CardsName.put(45, "7 spades");
			CardsName.put(46, "8 spades");
			CardsName.put(47, "9 spades");
			CardsName.put(48, "10 spades");
			CardsName.put(49, "Jack spades");
			CardsName.put(50, "Queen spades");
			CardsName.put(51, "King spades");
			CardsName.put(52, "Ace spades");
			/*CardsName.put(53, "2 clubs");
			CardsName.put(54, "3 clubs");
			CardsName.put(55, "4 clubs");
			CardsName.put(56, "5 clubs");
			CardsName.put(57, "6 clubs");
			CardsName.put(58, "7 clubs");
			CardsName.put(59, "8 clubs");
			CardsName.put(60, "9 clubs");
			CardsName.put(61, "10 clubs");
			CardsName.put(62, "Jack clubs");
			CardsName.put(63, "Queen clubs");
			CardsName.put(64, "King clubs");
			CardsName.put(65, "Ace clubs");
			CardsName.put(66, "2 diamonds");
			CardsName.put(67, "3 diamonds");
			CardsName.put(68, "4 diamonds");
			CardsName.put(69, "5 diamonds");
			CardsName.put(70, "6 diamonds");
			CardsName.put(71, "7 diamonds");
			CardsName.put(72, "8 diamonds");
			CardsName.put(73, "9 diamonds");
			CardsName.put(74, "10 diamonds");
			CardsName.put(75, "Jack diamonds");
			CardsName.put(76, "Queen diamonds");
			CardsName.put(77, "King diamonds");
			CardsName.put(78, "Ace diamonds");
			CardsName.put(79, "2 hearts");
			CardsName.put(80, "3 hearts");
			CardsName.put(81, "4 hearts");
			CardsName.put(82, "5 hearts");
			CardsName.put(83, "6 hearts");
			CardsName.put(84, "7 hearts");
			CardsName.put(85, "8 hearts");
			CardsName.put(86, "9 hearts");
			CardsName.put(87, "10 hearts");
			CardsName.put(88, "Jack hearts");
			CardsName.put(89, "Queen hearts");
			CardsName.put(90, "King hearts");
			CardsName.put(91, "Ace hearts");
			CardsName.put(92, "2 spades");
			CardsName.put(93, "3 spades");
			CardsName.put(94, "4 spades");
			CardsName.put(95, "5 spades");
			CardsName.put(96, "6 spades");
			CardsName.put(97, "7 spades");
			CardsName.put(98, "8 spades");
			CardsName.put(99, "9 spades");
			CardsName.put(100, "10 spades");
			CardsName.put(101, "Jack spades");
			CardsName.put(102, "Queen spades");
			CardsName.put(103, "King spades");
			CardsName.put(104, "Ace spades");*/
		
	}

}